repository.type=database

# Environment
app.env=development

# H2 Database
db.url=jdbc:h2:./quantitymeasurementdb;AUTO_SERVER=TRUE
db.username=sa
db.password=
db.driver=org.h2.Driver

# Connection pool
db.pool.max=10
db.pool.min=2