spring.profiles.active=local

server.port=${PORT:8761}
spring.application.name=service-registry

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=*