server.port=${PORT:8082}
spring.application.name=quantity-service

spring.profiles.active=local

# ========================
# DB CONFIG
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========================
# EUREKA CONFIG
# ========================
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOSTNAME:localhost}

spring.jpa.properties.hibernate.default_schema=quantity_schema
